apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-eks-cluster
  region: us-east-1
iam:
  withOIDC: true
vpc:
  id: "vpc-04f416c5115de5f2d" # Change to your VPC ID
  subnets:
    private:
      us-east-1a:
        id: "subnet-06dfb2529a14fa201"  # Change to your Subnet ID
      us-east-1b:
        id: "subnet-08e53258b6ffa3928"  # Change to your Subnet ID
nodeGroups:
  - name: my-ng
    privateNetworking: true
    subnets:
      - subnet-06dfb2529a14fa201 # Change to your Subnet ID
      - subnet-08e53258b6ffa3928 # Change to your Subnet ID
    instanceType: t3.medium
    desiredCapacity: 2
